import { useEffect, useState } from 'react';
import { Alert, Button, Card, Col, Descriptions, Divider, Form, Input, InputNumber, Row, Select, Space, Spin, Statistic, Table, Tabs, Tag, Typography, message } from 'antd';
import { Link, useParams } from 'react-router-dom';
import { apiClient } from '../../api/client';
import { declaredCoordinate, parameter, position, workspaceApi, type Antenna, type Cell, type Coordinate, type EnvironmentAsset, type Scenario, type Validation } from '../../api/workspace';
import { PageHeader } from '../../components/PageHeader';
import { AntennaPatternViewer } from './AntennaPatternViewer';

interface ProfileOption { profile_id: string; name: string; library: string; beam_type: string; beam_ids: number[]; artifact_id: string; artifact_hash: string }
interface RadioModelOption { backend: string; version: string; status: string; calibration_status: string; source: string; limitations: string[] }
const PROBLEMS = ['NETWORK_STRUCTURE', 'USER_ACCESS', 'SYSTEM_RESOURCE'];
const LAYER_KINDS = ['BASE_MAP', 'BUILDINGS', 'SITE', 'CELL', 'UE', 'RADIO', 'TRAFFIC', 'HANDOVER'];
const CORE_FIELDS = [
  ['carrier_frequency', '载波频率', 'Hz'], ['bandwidth', '带宽', 'Hz'], ['tx_power', '发射功率', 'dBm'],
  ['azimuth', '方位角', 'deg'], ['mechanical_tilt', '机械下倾', 'deg'], ['electrical_tilt', '电下倾', 'deg'], ['antenna_height', '天线高度', 'm'],
] as const;

function PositionFields() { return <Row gutter={8}>{(['x', 'y', 'z'] as const).map((axis) => <Col span={8} key={axis}><Form.Item name={axis} label={`${axis.toUpperCase()} / m`} rules={[{ required: true }]}><InputNumber style={{ width: '100%' }} /></Form.Item></Col>)}</Row>; }

export function WorkspaceEditorPage() {
  const { scenarioId = '' } = useParams();
  const [toast, context] = message.useMessage();
  const [scenario, setScenario] = useState<Scenario | null>(null);
  const [validation, setValidation] = useState<Validation | null>(null);
  const [assets, setAssets] = useState<EnvironmentAsset[]>([]);
  const [profiles, setProfiles] = useState<ProfileOption[]>([]);
  const [providerOptions, setProviderOptions] = useState<{ provider_type: string; status: string }[]>([]);
  const [radioModels, setRadioModels] = useState<RadioModelOption[]>([]);
  const [activeTab, setActiveTab] = useState('basic');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [instance, setInstance] = useState<{ instance_id: string; identity_hash: string; run_status: string } | null>(null);
  const [seed, setSeed] = useState(15);

  const refresh = async () => {
    try {
      const [row, check, assetRows, profileResponse, radioResponse] = await Promise.all([
        workspaceApi.get(scenarioId), workspaceApi.validation(scenarioId), workspaceApi.assets(),
        apiClient.get<{ items: ProfileOption[] }>('/workspace/antennas/a-matrix/options').catch(() => ({ data: { items: [] } })),
        apiClient.get<{ items: RadioModelOption[] }>('/workspace/radio/models').catch(() => ({ data: { items: [] } })),
      ]);
      setScenario(row); setValidation(check); setAssets(assetRows); setProfiles(profileResponse.data.items); setRadioModels(radioResponse.data.items); setError('');
      apiClient.get<{ items: { provider_type: string; status: string }[] }>('/workspace/antennas/providers').then(({ data }) => setProviderOptions(data.items)).catch(() => setProviderOptions([]));
    } catch (cause) { setError(String(cause)); }
  };
  useEffect(() => { void refresh(); }, [scenarioId]);

  const save = async (section: string, value: unknown) => {
    if (!scenario) return;
    setBusy(true);
    try {
      const row = await workspaceApi.patch(scenario.scenario_id, section, scenario.version, value);
      setScenario(row); setValidation(await workspaceApi.validation(row.scenario_id)); toast.success(`已保存 ${section} · v${row.version}`);
    } catch (cause) { toast.error(String(cause)); await refresh(); }
    finally { setBusy(false); }
  };
  const coordinate: Coordinate = scenario?.environment?.coordinate ?? declaredCoordinate('SIONNA_SCENE_CARTESIAN', 'm');
  const editable = scenario?.state !== 'ARCHIVED';
  if (error) return <Alert type="error" showIcon title="场景加载失败" description={error} action={<Button onClick={() => void refresh()}>重试</Button>} />;
  if (!scenario) return <Spin fullscreen description="加载场景配置" />;

  const basic = <Card title="基本信息"><Form key={`basic-${scenario.version}`} layout="vertical" initialValues={{ name: scenario.name, family: scenario.family }} onFinish={(values) => void save('basic', values)}><Row gutter={12}><Col xs={24} md={14}><Form.Item name="name" label="场景名称" rules={[{ required: true }]}><Input /></Form.Item></Col><Col xs={24} md={10}><Form.Item name="family" label="业务 Family"><Input /></Form.Item></Col></Row><Button htmlType="submit" type="primary" disabled={!editable} loading={busy}>保存基本信息</Button></Form><Divider /><Descriptions size="small" column={1}><Descriptions.Item label="场景 ID">{scenario.scenario_id}</Descriptions.Item><Descriptions.Item label="Definition Hash"><Typography.Text copyable code>{scenario.definition_hash}</Typography.Text></Descriptions.Item><Descriptions.Item label="来源候选">{scenario.candidate_hash ?? '空白配置，不来自 Day12 候选'}</Descriptions.Item><Descriptions.Item label="Lineage"><code>{JSON.stringify(scenario.lineage)}</code></Descriptions.Item></Descriptions></Card>;

  const environment = <Row gutter={16}><Col xs={24} xl={12}><Card title="环境配置 · 坐标语义必须显式声明"><Form key={`env-${scenario.version}`} layout="vertical" initialValues={{ environment_id: scenario.environment?.environment_id ?? '', asset_id: scenario.environment?.asset_id, coordinate_system: scenario.environment?.coordinate.coordinate_system === 'UNKNOWN' ? '' : scenario.environment?.coordinate.coordinate_system, unit: scenario.environment?.coordinate.unit === 'UNKNOWN' ? '' : scenario.environment?.coordinate.unit, origin: scenario.environment?.coordinate.origin === 'UNKNOWN' ? '' : scenario.environment?.coordinate.origin, layers: scenario.environment?.layers.filter((layer) => layer.visible).map((layer) => layer.kind) ?? [] }} onFinish={(values) => void save('environment', { environment_id: values.environment_id, asset_id: values.asset_id ?? null, coordinate: { coordinate_system: values.coordinate_system, unit: values.unit, origin: values.origin || 'USER_DECLARED', source: 'USER_DEFINED', status: 'DECLARED' }, layers: (values.layers ?? []).map((kind: string) => ({ layer_id: `${values.environment_id}-${kind}`, kind, visible: true, source_asset_id: values.asset_id ?? null, status: ['SITE', 'CELL', 'UE'].includes(kind) ? 'CONFIGURED_NOT_RENDERED' : values.asset_id ? 'ASSET_REGISTERED_NOT_RENDERED' : 'SOURCE_REQUIRED' })), supported_backends: [], version: scenario.environment?.version ?? 1 })}>
    <Form.Item name="environment_id" label="环境 ID" rules={[{ required: true }]}><Input placeholder="ENV-URBAN-001" /></Form.Item><Form.Item name="asset_id" label="已登记环境资产"><Select allowClear placeholder="可不绑定资产；不代表已加载地图" options={assets.map((asset) => ({ value: asset.asset_id, label: `${asset.name} · ${asset.asset_type} · ${asset.conversion_status}` }))} /></Form.Item><Form.Item name="coordinate_system" label="坐标系" rules={[{ required: true }]}><Input placeholder="例如 SIONNA_SCENE_CARTESIAN，需有依据" /></Form.Item><Form.Item name="unit" label="位置单位" rules={[{ required: true }]}><Input placeholder="例如 m" /></Form.Item><Form.Item name="origin" label="坐标原点"><Input placeholder="用户声明 / 数据说明" /></Form.Item><Form.Item name="layers" label="MapLayer 图层（配置可见性，不代表已渲染）"><Select mode="multiple" options={LAYER_KINDS.map((value) => ({ value, label: value }))} /></Form.Item><Button htmlType="submit" type="primary" disabled={!editable} loading={busy}>保存环境</Button></Form></Card></Col>
    <Col xs={24} xl={12}><Card title="登记已有环境文件（只读元数据，不转换）"><Form layout="vertical" onFinish={async (values) => { try { await workspaceApi.registerAsset({ name: values.name, asset_type: values.asset_type, source_path: values.source_path, coordinate: declaredCoordinate(values.coordinate_system, values.unit) }); toast.success('资产元数据已登记'); await refresh(); } catch (cause) { toast.error(String(cause)); } }}><Form.Item name="name" label="资产名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="asset_type" label="文件类型" rules={[{ required: true }]}><Select options={['OSM', 'GLTF', 'GEOJSON', 'RASTER_MAP', 'TERRAIN', 'SIONNA_SCENE', 'CUSTOM_MESH'].map((value) => ({ value, label: value }))} /></Form.Item><Form.Item name="source_path" label="服务器上已有文件的绝对路径" rules={[{ required: true }]}><Input /></Form.Item><Row gutter={8}><Col span={12}><Form.Item name="coordinate_system" label="坐标系" rules={[{ required: true }]}><Input /></Form.Item></Col><Col span={12}><Form.Item name="unit" label="单位" rules={[{ required: true }]}><Input /></Form.Item></Col></Row><Button htmlType="submit" disabled={!editable}>登记文件</Button></Form><Alert className="section-top" type="warning" title="登记不是导入或渲染" description="保存路径、大小、SHA-256 与可读元数据；未经转换与后端兼容确认，不能宣称环境已可运行。" /></Card></Col></Row>;

  const batchEdit = async (values: Record<string, string | number | string[]>) => {
    const field = String(values.parameter);
    const cellIds = Array.isArray(values.cell_ids) ? values.cell_ids.map(String) : [];
    const unit = CORE_FIELDS.find(([key]) => key === field)?.[2] ?? 'UNKNOWN';
    if (!cellIds.length) return;
    try {
      const updated = await workspaceApi.batchEditCells(scenario.scenario_id, scenario.version, cellIds, { [field]: parameter(Number(values.value), unit) });
      setScenario(updated); setValidation(await workspaceApi.validation(updated.scenario_id)); toast.success(`已批量更新 ${cellIds.length} 个小区，定义版本 v${updated.version}`);
    } catch (cause) { toast.error(String(cause)); await refresh(); }
  };

  const network = <Space orientation="vertical" style={{ width: '100%' }} size="large"><Row gutter={16}><Col xs={24} xl={12}><Card title={`站点 Sites · ${scenario.sites.length}`}><Form key={`sites-${scenario.version}`} layout="vertical" onFinish={(values) => void save('sites', [...scenario.sites, { site_id: values.site_id, name: values.name, position: position(values.x, values.y, values.z, coordinate), source: 'USER_DEFINED', version: 1 }])}><Row gutter={8}><Col span={12}><Form.Item name="site_id" label="站点 ID" rules={[{ required: true }]}><Input /></Form.Item></Col><Col span={12}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item></Col></Row><PositionFields /><Button htmlType="submit" disabled={!editable || !scenario.environment} loading={busy}>新增站点</Button></Form><Table size="small" rowKey="site_id" pagination={{ pageSize: 6 }} dataSource={scenario.sites} columns={[{ title: 'ID', dataIndex: 'site_id' }, { title: '位置', key: 'position', render: (_, row) => `${row.position.x}, ${row.position.y}, ${row.position.z}` }]} /></Card></Col>
    <Col xs={24} xl={12}><Card title={`小区 Cells · ${scenario.cells.length}`}><Form key={`cells-${scenario.version}`} layout="vertical" onFinish={(values) => { const core = Object.fromEntries(CORE_FIELDS.map(([key, , unit]) => [key, parameter(values[key] ?? null, unit)])); const cell: Cell = { cell_id: values.cell_id, site_id: values.site_id, name: values.name, position: null, core, antenna: { antenna_definition_id: values.antenna_definition_id ?? null, aau_definition_id: null, source: values.antenna_definition_id ? 'USER_DEFINED' : 'UNKNOWN' }, network_parameters: {}, resource_parameters: {}, backend_extensions: {}, source: 'USER_DEFINED', version: 1 }; void save('cells', [...scenario.cells, cell]); }}><Row gutter={8}><Col span={12}><Form.Item name="cell_id" label="小区 ID" rules={[{ required: true }]}><Input /></Form.Item></Col><Col span={12}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item></Col></Row><Row gutter={8}><Col span={12}><Form.Item name="site_id" label="所属站点" rules={[{ required: true }]}><Select options={scenario.sites.map((site) => ({ value: site.site_id, label: site.name }))} /></Form.Item></Col><Col span={12}><Form.Item name="antenna_definition_id" label="天线绑定"><Select allowClear options={scenario.antennas.map((antenna) => ({ value: antenna.antenna_definition_id, label: antenna.name }))} /></Form.Item></Col></Row><Row gutter={8}>{CORE_FIELDS.map(([key, label, unit]) => <Col xs={12} md={8} key={key}><Form.Item name={key} label={`${label} (${unit})`} rules={['carrier_frequency', 'bandwidth', 'tx_power'].includes(key) ? [{ required: true }] : []}><InputNumber style={{ width: '100%' }} /></Form.Item></Col>)}</Row><Button htmlType="submit" disabled={!editable || scenario.sites.length === 0} loading={busy}>新增小区</Button></Form><Table size="small" rowKey="cell_id" pagination={{ pageSize: 6 }} dataSource={scenario.cells} columns={[{ title: 'ID', dataIndex: 'cell_id' }, { title: '站点', dataIndex: 'site_id' }, { title: '天线', key: 'antenna', render: (_, row: Cell) => row.antenna.antenna_definition_id ?? '未绑定' }]} />
      <Divider>批量修改 Cell 参数</Divider><Form key={`batch-${scenario.version}`} layout="vertical" onFinish={(values) => void batchEdit(values)}><Form.Item name="cell_ids" label="目标小区" rules={[{ required: true }]}><Select mode="multiple" showSearch options={scenario.cells.map((cell) => ({ value: cell.cell_id, label: `${cell.cell_id} · ${cell.name}` }))} /></Form.Item><Row gutter={8}><Col span={12}><Form.Item name="parameter" label="参数" rules={[{ required: true }]}><Select options={CORE_FIELDS.map(([value, label]) => ({ value, label }))} /></Form.Item></Col><Col span={12}><Form.Item name="value" label="统一设置值" rules={[{ required: true }]}><InputNumber style={{ width: '100%' }} /></Form.Item></Col></Row><Button htmlType="submit" disabled={!editable || scenario.cells.length === 0}>批量应用并生成新定义版本</Button></Form></Card></Col></Row><Alert type="info" title="大规模配置" description="结构上站点包含小区；后端支持按小区 ID 批量参数编辑与版本冲突检查。千小区配置烟测不等于千小区物理仿真。" /></Space>;

  const antenna = <Row gutter={16}><Col xs={24} xl={10}><Card title="天线 Provider 与配置"><Alert type="info" className="section-bottom" title="Provider 边界" description="A-Matrix 相对响应已实现；Sionna Built-in、Gaussian、Custom、External 当前为接口契约。状态由后端返回。" />
    <Form key={`antenna-${scenario.version}`} layout="vertical" initialValues={{ provider_type: 'A_MATRIX' }} onFinish={(values) => {
      const provider = values.provider_type as string;
      const profile = profiles.find((item) => item.profile_id === values.profile_id);
      if (provider === 'A_MATRIX' && !profile) return;
      const implemented = provider === 'A_MATRIX' && !!profile;
      const definition: Antenna = {
        antenna_definition_id: values.antenna_definition_id, name: values.name, provider_type: provider,
        provider_status: implemented ? 'IMPLEMENTED' : 'CONTRACT_ONLY', source: implemented ? 'IMPORTED' : 'USER_DEFINED',
        beam_count: profile?.beam_ids.length ?? null, coordinate: declaredCoordinate('SIONNATEST_ANGULAR_GRID', 'deg'),
        normalization: implemented ? 'PEAK_LINEAR_POWER_TO_RELATIVE' : 'UNKNOWN', calibration_status: implemented ? 'RELATIVE_ONLY' : 'UNKNOWN',
        supported_backends: implemented ? ['FAST_PROPAGATION'] : [], artifact_id: profile?.artifact_id ?? null,
        artifact_hash: profile?.artifact_hash ?? null, profile_id: profile?.profile_id ?? null,
        parameters: profile ? { library: profile.library, beam_type: profile.beam_type } : {}, version: 1,
      };
      void save('antennas', [...scenario.antennas, definition]);
    }}>
      <Form.Item name="antenna_definition_id" label="天线定义 ID" rules={[{ required: true }]}><Input /></Form.Item>
      <Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item>
      <Form.Item name="provider_type" label="Provider 类型" rules={[{ required: true }]}><Select options={providerOptions.map((item) => ({ value: item.provider_type, label: `${item.provider_type} · ${item.status}` }))} /></Form.Item>
      <Form.Item noStyle shouldUpdate>{({ getFieldValue }) => getFieldValue('provider_type') === 'A_MATRIX' ? <Form.Item name="profile_id" label="A-Matrix Profile" rules={[{ required: true }]}><Select options={profiles.map((item) => ({ value: item.profile_id, label: `${item.name} · ${item.library} · ${item.beam_ids.length} beams` }))} /></Form.Item> : <Alert className="section-bottom" type="warning" title="契约 Provider" description="此定义可保存用于建模，但校验会阻止其进入可运行状态。" />}</Form.Item>
      <Button htmlType="submit" disabled={!editable || providerOptions.length === 0} loading={busy}>保存天线定义</Button>
    </Form><Divider /><Table size="small" rowKey="antenna_definition_id" pagination={false} dataSource={scenario.antennas} columns={[{ title: '定义', dataIndex: 'name' }, { title: 'Provider', dataIndex: 'provider_type' }, { title: '状态', dataIndex: 'provider_status' }, { title: 'Beam', dataIndex: 'beam_count' }]} /></Card></Col><Col xs={24} xl={14}><AntennaPatternViewer /></Col></Row>;

  const ue = <Card title={`UE 配置 · ${scenario.ues.length}`}><Form key={`ues-${scenario.version}`} layout="vertical" onFinish={(values) => void save('ues', [...scenario.ues, { ue_id: values.ue_id, position: position(values.x, values.y, values.z, coordinate), mobility: values.mobility, traffic_profile: values.traffic_profile, serving_cell_id: values.serving_cell_id ?? null, source: 'USER_DEFINED' }])}><Row gutter={8}><Col xs={24} md={8}><Form.Item name="ue_id" label="UE ID" rules={[{ required: true }]}><Input /></Form.Item></Col><Col xs={24} md={8}><Form.Item name="mobility" label="移动性" rules={[{ required: true }]}><Select placeholder="显式选择" options={[{ value: 'STATIC', label: '静态 · 当前仅支持几何配置' }, { value: 'MOBILITY_TRACE', label: '轨迹 · 未接入执行' }]} /></Form.Item></Col><Col xs={24} md={8}><Form.Item name="traffic_profile" label="业务 Profile" rules={[{ required: true }]}><Select placeholder="显式选择" options={[{ value: 'full_buffer', label: 'Full buffer · 声明' }, { value: 'custom', label: '自定义 · 未接入执行' }]} /></Form.Item></Col></Row><Form.Item name="serving_cell_id" label="Serving Cell（声明，不是切换结果）"><Select allowClear options={scenario.cells.map((cell) => ({ value: cell.cell_id, label: cell.cell_id }))} /></Form.Item><PositionFields /><Button htmlType="submit" disabled={!editable || !scenario.environment} loading={busy}>新增 UE</Button></Form><Table size="small" rowKey="ue_id" dataSource={scenario.ues} pagination={{ pageSize: 10 }} columns={[{ title: 'UE', dataIndex: 'ue_id' }, { title: '移动性', dataIndex: 'mobility' }, { title: '业务', dataIndex: 'traffic_profile' }, { title: '位置', key: 'position', render: (_, row) => row.position ? `${row.position.x}, ${row.position.y}, ${row.position.z}` : '未配置' }, { title: 'Serving', dataIndex: 'serving_cell_id', render: (value: string | null) => value ?? '未声明' }]} /></Card>;

  const traffic = <Card title="业务配置"><Form key={`traffic-${scenario.version}`} layout="vertical" initialValues={{ kind: scenario.traffic.kind === 'UNKNOWN' ? undefined : scenario.traffic.kind }} onFinish={(values) => void save('traffic', { kind: values.kind, availability: values.kind === 'FULL_BUFFER' ? 'AVAILABLE' : values.kind === 'MEASURED_TRAFFIC' ? 'EXTERNAL_DATA_REQUIRED' : 'NOT_IMPLEMENTED', source: 'USER_DEFINED' })}><Form.Item name="kind" label="业务类型" rules={[{ required: true }]}><Select placeholder="请选择，不会自动预设" options={[{ value: 'FULL_BUFFER', label: 'Full buffer · 当前可声明' }, { value: 'STATIC_DEMAND', label: 'Static demand · 未实现' }, { value: 'TIME_SERIES', label: 'Time series · 未实现' }, { value: 'BEAM_SPACE_PREDICTION', label: 'Beam-space prediction · 未实现' }, { value: 'MEASURED_TRAFFIC', label: 'Measured traffic · 外部数据依赖' }]} /></Form.Item><Button htmlType="submit" disabled={!editable}>保存业务</Button></Form><Typography.Paragraph type="secondary">业务定义不等于流量样本或仿真输入已就绪。</Typography.Paragraph></Card>;
  const radio = <Card title="无线模型"><Form key={`radio-${scenario.version}`} layout="vertical" initialValues={{ backend: scenario.radio.backend === 'UNKNOWN' ? undefined : scenario.radio.backend }} onFinish={(values) => { const model = radioModels.find((item) => item.backend === values.backend); if (!model) return; void save('radio', { backend: model.backend, status: model.status, version: model.version, calibration_status: model.calibration_status, source: model.source }); }}><Form.Item name="backend" label="已登记无线模型" rules={[{ required: true }]}><Select placeholder="请选择注册模型" options={radioModels.map((item) => ({ value: item.backend, label: `${item.backend} · ${item.status} · ${item.version}` }))} /></Form.Item><Button htmlType="submit" disabled={!editable || radioModels.length === 0} loading={busy}>保存无线模型声明</Button></Form><Descriptions className="section-top" column={1} bordered><Descriptions.Item label="后端">{scenario.radio.backend}</Descriptions.Item><Descriptions.Item label="模型版本">{scenario.radio.version}</Descriptions.Item><Descriptions.Item label="校准">{scenario.radio.calibration_status}</Descriptions.Item><Descriptions.Item label="执行接入"><Tag color="orange">Day15 配置尚未接入实验执行器</Tag></Descriptions.Item></Descriptions><Alert className="section-top" type="warning" title="无线数值边界" description="A-Matrix 的归一化相对响应不是 dBi、dBm 或实测 RSRP/SINR。Day14 现有无线观测仅使用明确的固定示例场景。模型已登记仍不等于执行器已接入。" /><Space className="section-top"><Link to="/scenarios/radio">查看 Day14 观测示例</Link><Link to="/scenarios/ue">查看 UE Twin 几何</Link></Space></Card>;
  const functions = <Card title="网络功能"><Form key={`functions-${scenario.version}`} layout="vertical" initialValues={{ functions: scenario.network_functions }} onFinish={(values) => void save('network_functions', values.functions ?? [])}><Form.Item name="functions" label="功能标签（声明）"><Select mode="tags" options={['USER_ASSOCIATION', 'RESOURCE_ALLOCATION', 'HANDOVER'].map((value) => ({ value }))} /></Form.Item><Button htmlType="submit" disabled={!editable}>保存网络功能声明</Button></Form><Alert className="section-top" type="info" title="声明不代表执行" description="选择 Handover 等标签只描述问题域，不会触发未实现的网络功能。" /></Card>;
  const optimization = <Card title="优化问题"><Form key={`optimization-${scenario.version}`} layout="vertical" initialValues={{ problems: scenario.optimization_problems }} onFinish={(values) => void save('optimization_problems', values.problems ?? [])}><Form.Item name="problems" label="问题类型"><Select mode="multiple" options={PROBLEMS.map((value) => ({ value }))} /></Form.Item><Button htmlType="submit" disabled={!editable}>保存问题类型</Button></Form></Card>;
  const preview = <Row gutter={16}><Col xs={24} xl={12}><Card title="配置预览"><Descriptions size="small" column={1} bordered><Descriptions.Item label="场景">{scenario.name}</Descriptions.Item><Descriptions.Item label="环境">{scenario.environment?.environment_id ?? '未配置'}</Descriptions.Item><Descriptions.Item label="站点 / 小区 / UE">{scenario.sites.length} / {scenario.cells.length} / {scenario.ues.length}</Descriptions.Item><Descriptions.Item label="天线 Provider">{scenario.antennas.map((item) => item.provider_type).join(', ') || '未配置'}</Descriptions.Item><Descriptions.Item label="业务">{scenario.traffic.kind}</Descriptions.Item><Descriptions.Item label="优化问题">{scenario.optimization_problems.join(', ') || '未配置'}</Descriptions.Item><Descriptions.Item label="定义版本">v{scenario.version}</Descriptions.Item></Descriptions></Card></Col><Col xs={24} xl={12}><Card title="空间预览 · 配置点位"><div style={{ minHeight: 330, position: 'relative', background: '#f4f7fb', border: '1px solid #dce4ee', borderRadius: 8, padding: 20 }}><Space orientation="vertical"><Tag color="blue">SITE × {scenario.sites.length}</Tag><Tag color="cyan">CELL × {scenario.cells.length}</Tag><Tag color="purple">UE × {scenario.ues.length}</Tag></Space><Typography.Paragraph className="section-top">点位来自配置，不是地图渲染或无线覆盖结果。环境资产转换与地图图层仍待接入。</Typography.Paragraph><Typography.Text code>{scenario.sites.slice(0, 5).map((item) => `${item.site_id} (${item.position.x}, ${item.position.y})`).join(' · ')}</Typography.Text></div></Card></Col></Row>;
  const verify = <Row gutter={16}><Col xs={24} xl={8}><Card title="三级校验"><Statistic title="配置结构" value={validation?.config_valid ? 'VALID' : 'INVALID'} /><Divider /><Statistic title="仿真后端接入" value={validation?.simulation_ready ? 'READY' : 'NOT READY'} /><Divider /><Statistic title="实验执行" value={validation?.experiment_ready ? 'READY' : 'NOT READY'} /><Divider /><InputNumber aria-label="实例 seed" value={seed} onChange={(value) => setSeed(value ?? 15)} style={{ width: 150 }} /><Button className="section-top" type="primary" disabled={!editable || !validation?.config_valid} onClick={async () => { try { const result = await workspaceApi.materialize(scenario.scenario_id, seed); setInstance(result); toast.success('定义快照已冻结；未执行仿真'); } catch (cause) { toast.error(String(cause)); } }}>冻结定义实例</Button>{instance && <Alert className="section-top" type="success" title={`实例 ${instance.instance_id}`} description={`状态 ${instance.run_status} · identity ${instance.identity_hash.slice(0, 16)}`} />}</Card></Col><Col xs={24} xl={16}><Card title="校验问题"><Table size="small" rowKey={(_, index) => String(index)} pagination={false} dataSource={validation?.issues ?? []} columns={[{ title: '级别', dataIndex: 'severity', render: (value: string) => <Tag color={value === 'ERROR' ? 'red' : 'gold'}>{value}</Tag> }, { title: '代码', dataIndex: 'code' }, { title: '路径', dataIndex: 'path' }, { title: '说明', dataIndex: 'message' }]} /></Card></Col></Row>;

  return <>{context}<PageHeader titleZh={scenario.name} titleEn={`Configured Scenario · ${scenario.scenario_id}`} subtitle={`状态 ${scenario.state} · version ${scenario.version} · definition ${scenario.definition_hash.slice(0, 12)} · 所有修改按 Section 保存`} extra={<Link to="/scenarios">返回场景库</Link>} /><Alert className="section-bottom" type="warning" showIcon title="科学边界" description="场景定义、冻结实例、运行、观测与验收证据是不同对象；本工作区不把保存配置解释成仿真执行。" /><Tabs activeKey={activeTab} onChange={setActiveTab} items={[
    { key: 'basic', label: '基础', children: basic }, { key: 'environment', label: '环境', children: environment }, { key: 'network', label: `网络 ${scenario.sites.length}/${scenario.cells.length}`, children: network },
    { key: 'antenna', label: '天线', children: antenna }, { key: 'ue', label: `UE ${scenario.ues.length}`, children: ue }, { key: 'traffic', label: '业务', children: traffic },
    { key: 'radio', label: '无线', children: radio }, { key: 'functions', label: '网络功能', children: functions }, { key: 'optimization', label: '优化问题', children: optimization },
    { key: 'preview', label: '预览', children: preview }, { key: 'validation', label: '校验', children: verify },
  ]} /></>;
}
