"""
Sionna RT 端到端演示 / Sionna RT end-to-end demo.

Usage:
    python scripts/run_sionna_demo.py [--config configs/sionna_demo.yaml] [--output-root outputs]
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from simulation import ScenarioConfig, SimulationError, new_experiment_id  # noqa: E402
from simulation.backends import get_backend  # noqa: E402
from simulation.runner import STEPS, run_experiment  # noqa: E402

LINE = "=" * 50
SEP = "-" * 50
STEP_LABELS = dict(STEPS)
STEP_INDEX = {key: i for i, (key, _) in enumerate(STEPS, start=1)}


class _NoTracebackFormatter(logging.Formatter):
    """控制台只显示一行错误信息，完整 traceback 保留在 run.log 中。"""

    def format(self, record: logging.LogRecord) -> str:
        saved = record.exc_info, record.exc_text
        record.exc_info, record.exc_text = None, None
        try:
            return super().format(record)
        finally:
            record.exc_info, record.exc_text = saved


def _print_step(step: str, status: str) -> None:
    if status == "RUNNING":
        return
    label = STEP_LABELS[step]
    print(f"[{STEP_INDEX[step]}/{len(STEPS)}] {label:<36} {status}", flush=True)


def _relative(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=REPO_ROOT / "configs" / "sionna_demo.yaml")
    parser.add_argument("--output-root", type=Path, default=REPO_ROOT / "outputs")
    parser.add_argument("-v", "--verbose", action="store_true", help="also print logs to console")
    args = parser.parse_args()

    console = logging.StreamHandler()
    console.setLevel(logging.INFO if args.verbose else logging.WARNING)
    formatter_cls = logging.Formatter if args.verbose else _NoTracebackFormatter
    console.setFormatter(formatter_cls("%(levelname)s [%(name)s] %(message)s"))
    logging.basicConfig(level=logging.INFO, handlers=[console])

    print(LINE)
    print("5G Learning Optimization Validation Platform")
    print("5G 网络学习优化仿真验证平台")
    print(LINE)

    try:
        config = ScenarioConfig.from_yaml(args.config)
        backend = get_backend(config.backend)
    except SimulationError as e:
        print(f"\nERROR: {e}\n\nSTATUS: FAILED")
        return 1

    health = backend.health_check()
    if not health["available"]:
        print("\nBackend not ready / 仿真后端不可用:")
        for err in health["errors"]:
            print(f"  - {err}")
        print("\nRun: python scripts/check_environment.py\n\nSTATUS: FAILED")
        return 1

    experiment_id = new_experiment_id()
    print(f"\nExperiment / 实验\n{experiment_id}")
    print(f"\nBackend / 仿真后端\nSionna RT {health['sionna_rt_version']} ({health['mitsuba_variant']})")
    print(f"\nScenario / 场景\n{config.name_en}\n{config.name_zh}")
    print(f"\n{SEP}\n")

    try:
        outcome = run_experiment(
            backend, config, args.output_root, on_step=_print_step, experiment_id=experiment_id
        )
    except SimulationError as e:
        print(f"\nERROR ({type(e).__name__}): {e}")
        print(f"See log: {_relative(args.output_root / experiment_id / 'run.log')}")
        print("\nSTATUS: FAILED")
        return 1

    result = outcome.result
    stats = result.metrics["radio_map"]
    print(f"\n{SEP}\n")
    runtime = result.runtime
    print("Runtime / 运行时间")
    print(f"simulation:      {runtime.simulation_seconds:.2f} s")
    print(f"artifact export: {runtime.artifact_export_seconds:.2f} s")
    print(f"total:           {runtime.total_seconds:.2f} s")
    print(f"\nRadio Map / 无线电地图 ({stats['metric'].upper()}, {stats['unit']})")
    print(
        f"min {stats['min']:.1f}  max {stats['max']:.1f}  mean {stats['mean']:.1f}  "
        f"coverage {stats['coverage_ratio'] * 100:.1f}% of {stats['num_cells']} cells"
    )
    print("\nArtifacts / 实验产物\n")
    for artifact in result.artifacts:
        print(_relative(outcome.output_dir / artifact.path))
    if result.warnings:
        print("\nWarnings / 警告")
        for w in result.warnings:
            print(f"  - {w}")
    print(f"\n{SEP}\n")
    print("Data provenance / 数据来源: [G] Generated by Sionna RT (simulation, measured=false)")
    print(f"\nSTATUS: {result.status.value.upper()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
